language: node_js
node_js:
  - stable
cache: npm

install:
  - yarn install

script:
  - yarn test

before_deploy:
  - npm install netlify-cli -g
  - yarn build

deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: master
